#!/bin/sh

if git diff --cached --quiet
then
	exit 0
fi

if which checkstyle >/dev/null
then
	exec git diff --cached --name-only | xargs checkstyle
else
	echo "Checkstyle not found, please setup the Belle2 Tools"
	exit 255
fi
